from transformers import GPT2LMHeadModel
import numpy as np


mapping = {
    "transformer.wte.weight": "embedding1.weights",
    "transformer.wpe.weight": "embedding2.weights",
    "transformer.h.0.ln_1.weight": "blocks.0.ln1.weight",
    "transformer.h.0.ln_1.bias": "blocks.0.ln1.bias",
    "transformer.h.0.attn.c_attn.weight": "blocks.0.attn.c_attn.weight",
    "transformer.h.0.attn.c_attn.bias": "blocks.0.attn.c_attn.bias",
    "transformer.h.0.attn.c_proj.weight": "blocks.0.attn.c_proj.weight",
    "transformer.h.0.attn.c_proj.bias": "blocks.0.attn.c_proj.bias",
    "transformer.h.0.ln_2.weight": "blocks.0.ln2.weight",
    "transformer.h.0.ln_2.bias": "blocks.0.ln2.bias",
    "transformer.h.0.mlp.c_fc.weight": "blocks.0.mlp.c_fc.weight",
    "transformer.h.0.mlp.c_fc.bias": "blocks.0.mlp.c_fc.bias",
    "transformer.h.0.mlp.c_proj.weight": "blocks.0.mlp.c_proj.weight",
    "transformer.h.0.mlp.c_proj.bias": "blocks.0.mlp.c_proj.bias",
    "transformer.h.1.ln_1.weight": "blocks.1.ln1.weight",
    "transformer.h.1.ln_1.bias": "blocks.1.ln1.bias",
    "transformer.h.1.attn.c_attn.weight": "blocks.1.attn.c_attn.weight",
    "transformer.h.1.attn.c_attn.bias": "blocks.1.attn.c_attn.bias",
    "transformer.h.1.attn.c_proj.weight": "blocks.1.attn.c_proj.weight",
    "transformer.h.1.attn.c_proj.bias": "blocks.1.attn.c_proj.bias",
    "transformer.h.1.ln_2.weight": "blocks.1.ln2.weight",
    "transformer.h.1.ln_2.bias": "blocks.1.ln2.bias",
    "transformer.h.1.mlp.c_fc.weight": "blocks.1.mlp.c_fc.weight",
    "transformer.h.1.mlp.c_fc.bias": "blocks.1.mlp.c_fc.bias",
    "transformer.h.1.mlp.c_proj.weight": "blocks.1.mlp.c_proj.weight",
    "transformer.h.1.mlp.c_proj.bias": "blocks.1.mlp.c_proj.bias",
    "transformer.h.2.ln_1.weight": "blocks.2.ln1.weight",
    "transformer.h.2.ln_1.bias": "blocks.2.ln1.bias",
    "transformer.h.2.attn.c_attn.weight": "blocks.2.attn.c_attn.weight",
    "transformer.h.2.attn.c_attn.bias": "blocks.2.attn.c_attn.bias",
    "transformer.h.2.attn.c_proj.weight": "blocks.2.attn.c_proj.weight",
    "transformer.h.2.attn.c_proj.bias": "blocks.2.attn.c_proj.bias",
    "transformer.h.2.ln_2.weight": "blocks.2.ln2.weight",
    "transformer.h.2.ln_2.bias": "blocks.2.ln2.bias",
    "transformer.h.2.mlp.c_fc.weight": "blocks.2.mlp.c_fc.weight",
    "transformer.h.2.mlp.c_fc.bias": "blocks.2.mlp.c_fc.bias",
    "transformer.h.2.mlp.c_proj.weight": "blocks.2.mlp.c_proj.weight",
    "transformer.h.2.mlp.c_proj.bias": "blocks.2.mlp.c_proj.bias",
    "transformer.h.3.ln_1.weight": "blocks.3.ln1.weight",
    "transformer.h.3.ln_1.bias": "blocks.3.ln1.bias",
    "transformer.h.3.attn.c_attn.weight": "blocks.3.attn.c_attn.weight",
    "transformer.h.3.attn.c_attn.bias": "blocks.3.attn.c_attn.bias",
    "transformer.h.3.attn.c_proj.weight": "blocks.3.attn.c_proj.weight",
    "transformer.h.3.attn.c_proj.bias": "blocks.3.attn.c_proj.bias",
    "transformer.h.3.ln_2.weight": "blocks.3.ln2.weight",
    "transformer.h.3.ln_2.bias": "blocks.3.ln2.bias",
    "transformer.h.3.mlp.c_fc.weight": "blocks.3.mlp.c_fc.weight",
    "transformer.h.3.mlp.c_fc.bias": "blocks.3.mlp.c_fc.bias",
    "transformer.h.3.mlp.c_proj.weight": "blocks.3.mlp.c_proj.weight",
    "transformer.h.3.mlp.c_proj.bias": "blocks.3.mlp.c_proj.bias",
    "transformer.h.4.ln_1.weight": "blocks.4.ln1.weight",
    "transformer.h.4.ln_1.bias": "blocks.4.ln1.bias",
    "transformer.h.4.attn.c_attn.weight": "blocks.4.attn.c_attn.weight",
    "transformer.h.4.attn.c_attn.bias": "blocks.4.attn.c_attn.bias",
    "transformer.h.4.attn.c_proj.weight": "blocks.4.attn.c_proj.weight",
    "transformer.h.4.attn.c_proj.bias": "blocks.4.attn.c_proj.bias",
    "transformer.h.4.ln_2.weight": "blocks.4.ln2.weight",
    "transformer.h.4.ln_2.bias": "blocks.4.ln2.bias",
    "transformer.h.4.mlp.c_fc.weight": "blocks.4.mlp.c_fc.weight",
    "transformer.h.4.mlp.c_fc.bias": "blocks.4.mlp.c_fc.bias",
    "transformer.h.4.mlp.c_proj.weight": "blocks.4.mlp.c_proj.weight",
    "transformer.h.4.mlp.c_proj.bias": "blocks.4.mlp.c_proj.bias",
    "transformer.h.5.ln_1.weight": "blocks.5.ln1.weight",
    "transformer.h.5.ln_1.bias": "blocks.5.ln1.bias",
    "transformer.h.5.attn.c_attn.weight": "blocks.5.attn.c_attn.weight",    
    "transformer.h.5.attn.c_attn.bias": "blocks.5.attn.c_attn.bias",
    "transformer.h.5.attn.c_proj.weight": "blocks.5.attn.c_proj.weight",
    "transformer.h.5.attn.c_proj.bias": "blocks.5.attn.c_proj.bias",
    "transformer.h.5.ln_2.weight": "blocks.5.ln2.weight",
    "transformer.h.5.ln_2.bias": "blocks.5.ln2.bias",
    "transformer.h.5.mlp.c_fc.weight": "blocks.5.mlp.c_fc.weight",
    "transformer.h.5.mlp.c_fc.bias": "blocks.5.mlp.c_fc.bias",
    "transformer.h.5.mlp.c_proj.weight": "blocks.5.mlp.c_proj.weight",
    "transformer.h.5.mlp.c_proj.bias": "blocks.5.mlp.c_proj.bias",
    "transformer.h.6.ln_1.weight": "blocks.6.ln1.weight",
    "transformer.h.6.ln_1.bias": "blocks.6.ln1.bias",
    "transformer.h.6.attn.c_attn.weight": "blocks.6.attn.c_attn.weight",
    "transformer.h.6.attn.c_attn.bias": "blocks.6.attn.c_attn.bias",
    "transformer.h.6.attn.c_proj.weight": "blocks.6.attn.c_proj.weight",
    "transformer.h.6.attn.c_proj.bias": "blocks.6.attn.c_proj.bias",
    "transformer.h.6.ln_2.weight": "blocks.6.ln2.weight",
    "transformer.h.6.ln_2.bias": "blocks.6.ln2.bias",
    "transformer.h.6.mlp.c_fc.weight": "blocks.6.mlp.c_fc.weight",
    "transformer.h.6.mlp.c_fc.bias": "blocks.6.mlp.c_fc.bias",
    "transformer.h.6.mlp.c_proj.weight": "blocks.6.mlp.c_proj.weight",
    "transformer.h.6.mlp.c_proj.bias": "blocks.6.mlp.c_proj.bias",
    "transformer.h.7.ln_1.weight": "blocks.7.ln1.weight",
    "transformer.h.7.ln_1.bias": "blocks.7.ln1.bias",
    "transformer.h.7.attn.c_attn.weight": "blocks.7.attn.c_attn.weight",
    "transformer.h.7.attn.c_attn.bias": "blocks.7.attn.c_attn.bias",
    "transformer.h.7.attn.c_proj.weight": "blocks.7.attn.c_proj.weight",
    "transformer.h.7.attn.c_proj.bias": "blocks.7.attn.c_proj.bias",
    "transformer.h.7.ln_2.weight": "blocks.7.ln2.weight",
    "transformer.h.7.ln_2.bias": "blocks.7.ln2.bias",
    "transformer.h.7.mlp.c_fc.weight": "blocks.7.mlp.c_fc.weight",
    "transformer.h.7.mlp.c_fc.bias": "blocks.7.mlp.c_fc.bias",
    "transformer.h.7.mlp.c_proj.weight": "blocks.7.mlp.c_proj.weight",
    "transformer.h.7.mlp.c_proj.bias": "blocks.7.mlp.c_proj.bias",
    "transformer.h.8.ln_1.weight": "blocks.8.ln1.weight",
    "transformer.h.8.ln_1.bias": "blocks.8.ln1.bias",
    "transformer.h.8.attn.c_attn.weight": "blocks.8.attn.c_attn.weight",
    "transformer.h.8.attn.c_attn.bias": "blocks.8.attn.c_attn.bias",
    "transformer.h.8.attn.c_proj.weight": "blocks.8.attn.c_proj.weight",
    "transformer.h.8.attn.c_proj.bias": "blocks.8.attn.c_proj.bias",
    "transformer.h.8.ln_2.weight": "blocks.8.ln2.weight",
    "transformer.h.8.ln_2.bias": "blocks.8.ln2.bias",
    "transformer.h.8.mlp.c_fc.weight": "blocks.8.mlp.c_fc.weight",
    "transformer.h.8.mlp.c_fc.bias": "blocks.8.mlp.c_fc.bias",
    "transformer.h.8.mlp.c_proj.weight": "blocks.8.mlp.c_proj.weight",
    "transformer.h.8.mlp.c_proj.bias": "blocks.8.mlp.c_proj.bias",
    "transformer.h.9.ln_1.weight": "blocks.9.ln1.weight",
    "transformer.h.9.ln_1.bias": "blocks.9.ln1.bias",
    "transformer.h.9.attn.c_attn.weight": "blocks.9.attn.c_attn.weight",
    "transformer.h.9.attn.c_attn.bias": "blocks.9.attn.c_attn.bias",
    "transformer.h.9.attn.c_proj.weight": "blocks.9.attn.c_proj.weight",
    "transformer.h.9.attn.c_proj.bias": "blocks.9.attn.c_proj.bias",
    "transformer.h.9.ln_2.weight": "blocks.9.ln2.weight",
    "transformer.h.9.ln_2.bias": "blocks.9.ln2.bias",
    "transformer.h.9.mlp.c_fc.weight": "blocks.9.mlp.c_fc.weight",
    "transformer.h.9.mlp.c_fc.bias": "blocks.9.mlp.c_fc.bias",
    "transformer.h.9.mlp.c_proj.weight": "blocks.9.mlp.c_proj.weight",
    "transformer.h.9.mlp.c_proj.bias": "blocks.9.mlp.c_proj.bias",
    "transformer.h.10.ln_1.weight": "blocks.10.ln1.weight",
    "transformer.h.10.ln_1.bias": "blocks.10.ln1.bias",
    "transformer.h.10.attn.c_attn.weight": "blocks.10.attn.c_attn.weight",
    "transformer.h.10.attn.c_attn.bias": "blocks.10.attn.c_attn.bias",
    "transformer.h.10.attn.c_proj.weight": "blocks.10.attn.c_proj.weight",
    "transformer.h.10.attn.c_proj.bias": "blocks.10.attn.c_proj.bias",
    "transformer.h.10.ln_2.weight": "blocks.10.ln2.weight",
    "transformer.h.10.ln_2.bias": "blocks.10.ln2.bias",
    "transformer.h.10.mlp.c_fc.weight": "blocks.10.mlp.c_fc.weight",
    "transformer.h.10.mlp.c_fc.bias": "blocks.10.mlp.c_fc.bias",
    "transformer.h.10.mlp.c_proj.weight": "blocks.10.mlp.c_proj.weight",
    "transformer.h.10.mlp.c_proj.bias": "blocks.10.mlp.c_proj.bias",
    "transformer.h.11.ln_1.weight": "blocks.11.ln1.weight",
    "transformer.h.11.ln_1.bias": "blocks.11.ln1.bias",
    "transformer.h.11.attn.c_attn.weight": "blocks.11.attn.c_attn.weight",
    "transformer.h.11.attn.c_attn.bias": "blocks.11.attn.c_attn.bias",
    "transformer.h.11.attn.c_proj.weight": "blocks.11.attn.c_proj.weight",
    "transformer.h.11.attn.c_proj.bias": "blocks.11.attn.c_proj.bias",
    "transformer.h.11.ln_2.weight": "blocks.11.ln2.weight",
    "transformer.h.11.ln_2.bias": "blocks.11.ln2.bias",
    "transformer.h.11.mlp.c_fc.weight": "blocks.11.mlp.c_fc.weight",
    "transformer.h.11.mlp.c_fc.bias": "blocks.11.mlp.c_fc.bias",
    "transformer.h.11.mlp.c_proj.weight": "blocks.11.mlp.c_proj.weight",
    "transformer.h.11.mlp.c_proj.bias": "blocks.11.mlp.c_proj.bias",
    "transformer.ln_f.weight": "ln_out.weight",
    "transformer.ln_f.bias": "ln_out.bias",
    "lm_head.weight": "linear_out.weights"
}

weights_dict = {}
if __name__ == "__main__":
    model_hf = GPT2LMHeadModel.from_pretrained("gpt2")

    weights = model_hf.state_dict()

    for key, value in weights.items():
        if key in mapping:
            weights_dict[mapping[key]] = {
                "shape": np.array(value.detach().numpy().shape, dtype=np.int32).tobytes(), 
                "data": value.detach().numpy().flatten().tobytes()
            }
        else:
            print(f"Key {key} not in mapping")

    with open("weights.bin", "wb") as f:
        for key, value in weights_dict.items():
            f.write(key.encode("utf-8"))
            f.write(value["shape"])
            f.write(value["data"])